# =========================
# Organigramme
# =========================
spring.application.name=organigramme
spring.datasource.url=jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
# =========================
# H2 Console
# =========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# =========================
# Serveur / Profil
# =========================
server.port=8080
spring.profiles.active=dev

# =========================
# Springdoc OpenAPI (Swagger)
# =========================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
